### ISSUE TITLE
Terraform Plan not showing complete details of what is being created on cloud.

### ISSUE THREAD

**Issue by kaly2305** [rubrikinc/terraform-provider-polaris#48]
When we manually add account , Polaris will generate cloud formation template and in that template we can see what resources getting created on the cloud. In similar way, why terraform plan is not showing these details.
 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Terraform plan should describe all the details like what is being onboarded or created on cloud.

**Describe alternatives you've considered**
Execution of CloudFormation template manually instead of using TF for automation.

**Additional context**

**Comment by johan3141592** [comment]
Hi @kaly2305, the CloudFormation template is not created by Terraform and can therefore not be displayed as a diff. The TF provider gets the CloudFormation template from Polaris/RSC as a step in the process of adding the AWS account, this happens when the terraform apply is already running, i.e. after the user has accepted the changes to be applied.

**Comment by johan3141592** [comment]
It's now possible to add an AWS account to RSC without using a CloudFormation template, giving the user more control of what is being created. A guide can be found [here](https://registry.terraform.io/providers/rubrikinc/polaris/latest/docs/guides/aws_cnp_account).
